---
apiVersion: v1
kind: Service
metadata:
  name: option1-service
spec:
  type: NodePort
  selector:
    app: option1
  ports:
    - protocol: TCP
      nodePort: 30003
      port: 80
      targetPort: http 
